### ISSUE TITLE
How to accept self signed certificate

### ISSUE THREAD

**Issue by psmit** [CleverCloud/lapin#286]
When connecting with amqps, is there a way to allow self signed certificates? At this moment this fails with:

> Custom { kind: Other, error: Ssl(Error { code: ErrorCode(1), cause: Some(Ssl(ErrorStack([Error { code: 337047686, library: "SSL routines", function: "tls_process_server_certificate", reason: "certificate verify failed", file: "ssl/statem/statem_clnt.c", line: 1913 }]))) }, X509VerifyResult { code: 19, error: "self signed certificate in certificate chain" }) }

**Comment by Keruspe** [comment]
You're probably looking for https://docs.rs/lapin/1.0.2/lapin/struct.Connection.html#method.connect_with_config

**Comment by psmit** [comment]
Yes, I did find that method, but the only thing I can do there is passing new roots. Is there a way to accept any root?

**Comment by Keruspe** [comment]
There currently is no way to disable certificate verification, but doesn't it work if you just add you certificate chain here? It doesn't replace the roots, it just adds the chain of authenticity used to generate your certificate so that it can be trusted

**Comment by Keruspe** [comment]
If you really don't want to do that you can configure the TLS connector using somehting like this: https://github.com/CleverCloud/lapin/blob/master/examples/custom_tls_connection.rs
