### ISSUE TITLE
Add autoack to basic consume

### ISSUE THREAD

**Issue by asevans48** [CleverCloud/lapin#293]
Many clients, including in the tutorials using Python and Java on the RabbitMQ site, include the autoack feature in the _basic_consume_ method. Is it possible to add this to channel's basic_consume method?

**Comment by Keruspe** [comment]
Hi,

This is what you're looking for: https://docs.rs/lapin/1.2.1/lapin/options/struct.BasicConsumeOptions.html#structfield.no_ack

**Comment by Keruspe** [comment]
https://www.rabbitmq.com/amqp-0-9-1-reference.html#domain.no-ack
