### ISSUE TITLE
question: heartbeat: Is connection between the server handled in a separate thread?

### ISSUE THREAD

**Issue by zhiburt** [CleverCloud/lapin#299]
I am not proficient in `async` rust (as well as in general :cry:) so sorry in case I am wrong somewhere in basics.

As I understand by default reactors(`tokio`, etc.) uses one thread to handle `async` stuff. If `lapin` does networking with a `rabbitmq` server in main thread long sync jobs can cause a timeout of heartbeat.

Does `lapin` handle networking in a separate thread?

PS: I did go through the code but didn't come to the answer :disappointed: 

Thank you for the crate

**Comment by Keruspe** [comment]
Did you actually hit such a timeout?
Do you use an external runtime integration such as async-amqp, tokio-amqp or lapinou?
By default the heartbeat is handled by the same thread that handles the IO events, which is a separate thread spawned by lapin.

https://github.com/CleverCloud/lapin/blob/master/src/reactor.rs#L124

The heartbeat.poll_timeout() here sends the heartbeat if necessary, or tells poll not to block for too long to be able to send the next heartbeat just when we should

**Comment by zhiburt** [comment]
> Did you actually hit such a timeout?

I haven't, that question just naturally came to my mind.

> Do you use an external runtime integration such as `async-amqp`, `tokio-amqp` or `lapinou`?

Yes I am using a `tokio` integration.

> By default the heartbeat is handled by the same thread that handles the IO events, which is a separate thread spawned by lapin.

So if it's done in a separate thread I guess there should be no worries :+1: 

Here's an example of the concern I had

```
    consumer.set_delegate(move |delivery: DeliveryResult| async {
         // emulate a long sync work
         //
         // by default heartbeat timeout is 60 seconds so
         // if it would handled in the same thread the connection on the server would be closed?
         thread::sleep_ms(1000 * 60)
    })?;
```

**Comment by Keruspe** [comment]
Yup, that won't run in the same thread.

Do not though that AMQP heartbeat have two particularities:
- If you configure the heartbeat to be 60s, the actual time between two heartbeats on idle will be 30s, half the configured time (and if 60s have passed, the connection is considered as failed)
- No heartbeat frame is sent as long as other frames are sent. A heartbeat frame will be sent only if we didn't send anything for e.g. 30s if it's configured as 60s.

**Comment by zhiburt** [comment]
I might be a bad question but just to be better tuned.

Does all runtime integrations follow the same internal logic as the default runtime?
So `Yup, that won't run in the same thread.` would be true for each runtime?
> I haven't gone over code :disappointed:

**Comment by Keruspe** [comment]
Tokio and bastion only switch which executor is used, it's not yet possible to hook properly in their reactor, so yes.
For smol and async-std, we basically spawn a task on the executor which can be summarized as:

```
loop {
     Timer::new(heartbeat.poll_interval()).await
}
```

Meaning that this task should get awaken by the executor at the right time to trigger the heartbeat the same way the internal lapin's reactor does. The only caveat here is that if you do blocking stuff inside all the threads of the executor at the same time, you could get in trouble, but the heartbeat won't be your biggest concern when this time comes. Using blocking::unblock for such tasks should always be preferred anyways: https://docs.rs/blocking/0.6.1/blocking/fn.unblock.html

**Comment by zhiburt** [comment]
Thank you @Keruspe for these clarifications.
And sorry for bothering.

I will close the issue
