### ISSUE TITLE
Errors on publish

### ISSUE THREAD

**Issue by jothan** [CleverCloud/lapin#302]
My application consumes two streams that end up publishing to the same channel concurrently. Sometimes, a few times per day, the following error happens and drops the connection:

```2020-09-18 05:23:09-0400 ERROR lapin on_error called: ProtocolError(AMQPError { kind: Hard(UNEXPECTEDFRAME), message: ShortString("UNEXPECTED_FRAME - expected content body, got non content body frame instead") })```

I can reproduce the issue with the following code. The only difference is that my application only publishes once the connection is up.

```rust
use futures::prelude::*;

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let uri = std::env::var("RABBIT_URL")?;
    let conn = lapin::Connection::connect(&uri, Default::default()).await?;
    leak(conn).await
}

async fn leak(conn: lapin::Connection) -> Result<(), Box<dyn std::error::Error>> {
    let chan = conn.create_channel().await?;
    chan.confirm_select(Default::default()).await?;

    futures::stream::iter(0..1000).map(Ok::<_, lapin::Error>).try_for_each_concurrent(100, |_| async {
        chan.exchange_declare("devnull", lapin::ExchangeKind::Topic, Default::default(), Default::default()).await?;
        let confirm_future = chan.basic_publish("devnull", "42", Default::default(), b"Silly wabbit".to_vec(), Default::default()).await?;
        confirm_future.await?;
        Ok(())
    }).await?;

    chan.close(200, "bye").await?;
    conn.close(200, "bye").await?;

    Ok(())
}
```

**Comment by Keruspe** [comment]
There might be room for improvement when there are huge payloads. I have some local tests going on but the issue should be fixed

**Comment by jothan** [comment]
Looks good on my end, feel free to close this.

**Comment by Keruspe** [comment]
Thanks!
