### ISSUE TITLE
Channel into_iter works only ones but is it supposed to?

### ISSUE THREAD

**Issue by zhiburt** [CleverCloud/lapin#305]
I was thinking that the loop will work generally indefinitely until it get some network issue but it seems like works only 1 iteration. I could imagine that is considered an expected behavior but I am not sure so I opened the issue.

```rust
#[tokio::main]
async fn main() {
    let conn = rabbit_conn().await.expect("cann't connect to rabbitmq");
    let ch = rabbit_channel(&conn).await.expect("rabbitmq: cannot create a consumer channel");

    // loop works only 1 iteration
    for delivery in ch {
    
    }
}
```

```log
 2020-10-05T21:19:46.676Z WARN  pinky_swear > Failed resolving promise, promise has vanished. promise= error=sending on a closed channel 
```

PS: I haven't found implementation of IntoIter :disappointed:

**Comment by Keruspe** [comment]
There is no IntoIter implementation on Channel, only on Consumer.

**Comment by Keruspe** [comment]
Btw, which version of lapin are you using? 1.4.1 might fix your issue

**Comment by zhiburt** [comment]
It seems works with `1.4.1` I used `1.3.1`.

And yes I meant `Consumer` :(

I'll close the issue, Thank you
