### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by jlgerber** [CleverCloud/lapin#308]
It would be very helpful to at least provide the canonical tutorial examples [here](https://www.rabbitmq.com/getstarted.html) in Rust. Also, there are so many back ends for Lapin, but no advice on what to use when. 

I am having to look at other languages and intuit what to do here, but I am not quite sure which language to look at.

Given the amount of work put into this it is a shame that there is no documentation to speak of.

**Comment by Keruspe** [comment]
I am not even sure what the process here to publish documentation on rabbitmq.com is. I'm pretty sure that this is all done by Pivotal (the company that owns rabbitmq) and I'm not affiliated at all with them.

What exactly do you call "back ends"?

**Comment by jlgerber** [comment]
I don't think you have to publish the examples on rabbitmq. Just provide matching examples in the crate.

Sorry, by back ends, I really meant competing async backends - async_std, smol, etc. I know that a ton of work went into these crates. As a new user, I was a bit overwhelmed by the choices. Perhaps this is, in part, a large ecosystem discussion.

**Comment by Keruspe** [comment]
I think there is a confusion here. Those are not backends for lapin *at all*.

In rust, there are several async runtimes available (which are not linked in any way to lapin).

Lapin comes with its own executor and event loop, and allows you to use the ones from your runtime of choice if your application is already using one. It's purely optional and it's an intégration matter wrt the rest of your application. If your application isn't already using tokio or async-std or smol, you shouldn't even look at these yet.

This is really not related to lapin at all.

**Comment by jlgerber** [comment]
I see. thank you. 

When you say, Lapin comes with its own executor and event loop, as a noob it was a bit hard to intuit that, given the fact that all of the examples seem to leverage an external executor. 
All the examples in the examples directory that use futures seem to rely on the `futures_executor` crate. Is this leveraging an internal executor somehow?

Anyway, thank you for answering my questions. Very helpful. 

I was incredibly excited to find this crate, as we rely on Rabbit extensively at work, and I have been itching to swap out some python for Rust. Thank you for this - really great.

**Comment by Keruspe** [comment]
I see how that can be confusing.
Lapin comes with its own executor and event loop *for its internal tasks* but you still need another one for your main program, when running in async mode. There is also a sync mode (e.g. not based on futures) but it's deprecated and is fully gone in the future 2.0, which is why there o my is one example which is not really advertised on purpose.

Btw, if some example from the rabbitmq documentation would be useful as examples for lapin, please name those and I'll give it a look (or even better, you could try and write the examples yourself as an exercise, and I can help if you struggle to find out an equivalent of something in lapin)

**Comment by jlgerber** [comment]
Thank you.

I am currently going through the canonical rabbit examples and porting them from python to rust using lapin and will bug you about them at some point.

**Comment by Keruspe** [comment]
Contributions to the documentation and examples are always welcome. In the meantime, I don't think it's useful to keep this open
