### ISSUE TITLE
example in lapin docs does not compile

### ISSUE THREAD

**Issue by jlgerber** [CleverCloud/lapin#309]
after adding all of the dependencies, I get 
```
src/main.rs1:35

use futures_executor::{LocalPool, ThreadPool};
No ThreadPool in the root
```

**Comment by Keruspe** [comment]
Did you enable the thread-pool feature of futures-executor like it is in our dev-dependencies?

**Comment by jlgerber** [comment]
No, as that was not spelled out in the documentation. Although i figured it out after filing this ticket. I have seen this implied context in documentation trip up a lot of developers in the rust ecosystem.

**Comment by Keruspe** [comment]
Well, given examples are supposed to be run within lapin's repository using e.g. `cargo run --example=client`, I don't think this issue is relevant. The use of futures-executor or any other executor is not really relevant to lapin, it's a detaill left to the user, it has nothing to do in lapin's documentation imo

**Comment by jlgerber** [comment]
I am referring to the example in your documentation, not in your repository. Don't you think its worthwhile to add a one liner that mentions the dependencies required to run the example? Especially if the dependency itself requires configuration? Even a simple "see examples/Crate.toml for configuration"?

**Comment by Keruspe** [comment]
I genuinely do not understand what you're saying.

If your neither speaking of an example in the examples folder nor the one in README.md, I have no idea which example you're complaining about

**Comment by jlgerber** [comment]
Sorry. I am referring to the example in the rendered docs here:
https://docs.rs/lapin/1.4.2/lapin/?search=
vs the README.md

**Comment by jlgerber** [comment]
I see what is going on. On github, I am looking at `master` instead of the 1.4.2 tag. that accounts for the difference.

**Comment by Keruspe** [comment]
I'll improve that for next release!
