### ISSUE TITLE
Thoughts on rpc pattern?

### ISSUE THREAD

**Issue by jlgerber** [CleverCloud/lapin#310]
Having gone through the exercise of porting the tutorial examples on the main rabbitmq site to lapin & rust, there is one which I am having a bit of trouble with - rpc. The way that the rpc pattern works is apparently that the sender creates an exclusive anonymous queue which it hands off to the consumer, providing a correlation_id and a reply _to as part of the basic_publish call.
The issue that i am having is that while I have successfully round tripped data, i am not really able to do anything meaningful (ie update state outside of the closure) with the results. I have created a consumer for the queue on which data returns, and have used the set_delegate method on the Consumer returned from the basic_consume call in the sender, but that delegate is Fn not FnOnce or FnMut, so it doesn't seem like I can capture anything from the outer scope. So while i am able to confirm returned results via printing, I dont see how to really make use of the data...

Also, I am not sure how i block the main thread from returning prematurely, since the return computation is happening in a moved closure. 

For reference, the code lives here:
https://github.com/jlgerber/rustyRabbitEgs
 under 6-rpc/rust/rpc/src/*/bin/*

And the exercise in question is this one:
https://www.rabbitmq.com/tutorials/tutorial-six-go.html

Thoughts?

**Comment by jlgerber** [comment]
Sorry, I realized from your other examples that I could use soemthing like:
```
 let handle = task::spawn(async move {
        let mut consumer_iter = consumer.into_iter();
        while let Some(delivery_result) = consumer_iter.next() {
            if let Ok((_channel, delivery)) = delivery_result {
                let val = std::str::from_utf8(&delivery.data);
                if let Ok(value) = val {
                    println!("[x] {}: f({}) = {}",delivery.routing_key, guess_c, value);
                    println!("correlation_id: {}",&cid);
                } else {
                    println!("unable to convert raw data from delivery to string");
                }
            } else {
                println!("unable to convert raw data from delivery to string");
            }
            break;
        }

    });
```
instead of 
```
consumer.set_delegate
```
and the pattern works.

**Comment by Keruspe** [comment]
In an async context, you should use StreamExt and do consumer.next().await instead of using the consumer_iterator which is blocking.

But yeah, set_delegate basically spawns a new task on the executor for each delivery and leaves the handling to lapin. If you use set_delegate, you should use connection.run() to block until you call connection.close() somewhere

**Comment by Keruspe** [comment]
I guess we can close this one?

**Comment by brandonros** [comment]
Would be cool if there was a really clear example showing how to handle reply_to / correlation_id, kind of like: https://github.com/jgallagher/amiquip/blob/main/examples/rpc_client.rs

**Comment by Keruspe** [comment]
Should be easy enough to do. Want to give it a try? I can assist you with specifics if you're blocked while trying

**Comment by brandonros** [comment]
I’m stuck on only getting the response I want back on the consumer side. A quick web search let’s me believe that I need to use routing key? Is that right? I don’t want the consumer to listen to 100 messages it doesn’t need to receive when I’m only waiting for the response of one correlation ID for performance reasons. Does that make sense?
