### ISSUE TITLE
Delivery::acker field is public, but Acker struct is private

### ISSUE THREAD

**Issue by epwalsh** [CleverCloud/lapin#313]
The `Delivery::acker` field is public, but the `Acker` struct itself is private. This in and of itself is not really an issue, but we have some tests in Rusty Celery (https://github.com/rusty-celery/rusty-celery/blob/b0e4eaa9eed21df97da5e9bc4fec93fca9e0f315/src/broker/amqp.rs#L622-L629) that depend on creating mock `Delivery` objects directly, but now there is no way to create `Delivery` objects directly.

An alternative to making the `Acker` struct public would be to provide some public helper method for creating `Delivery`s. Perhaps [`Delivery::new`](https://github.com/CleverCloud/lapin/blob/0142098d1882ebf0924448b85037faee6354e345/src/message.rs#L55) could be public?

Then again, I understand if you don't want a public way of creating `Delivery`s. The only downside in Rusty Celery is we will lose some test coverage.

**Comment by Keruspe** [comment]
Hi,

You should be able to use Default::default()
