### ISSUE TITLE
Reconnect Socket error

### ISSUE THREAD

**Issue by davidhorac3** [CleverCloud/lapin#314]
Hi, I'm trying to connect with simple loop with async_std which waits till rabbit is started:

    loop {
        if let Ok(conn) = Connection::connect(
            "amqp://rabbit:5672",
            ConnectionProperties::default().with_async_std()
        ).await {
            return conn;
        }
    
        task::sleep(Duration::from_secs(2)).await;
    }
    
If rabbit is already running, it's ok and successfully connects at 1st attempt, but if rabbit is starting up then 'connect' method ends in endless loop with error: 'Socket was readable but we read 0, marking as wouldblock'.

It does not recover even after rabbit is started and just endlessly spam that error.
Also this appears only when connect method is called while the rabbit is starting up, when I prolong sleep to 10sec for example, to give rabbit enough time to start, it connects successfully.

**Comment by davidhorac3** [comment]
Found a workaround with timeout:

    loop {
        let connect_call = Connection::connect(
            "amqp://rabbit:5672",
            ConnectionProperties::default().with_async_std()
        );
        
        if let Ok(conn) = async_std::future::timeout(Duration::from_secs(1), conn_call).await {
            return conn;
        }
    
        task::sleep(Duration::from_secs(2)).await;
    }

It interrupts that 'Socket was readable but we read 0, marking as wouldblock' after a second, but it's not a very nice solution.

**Comment by davidhorac3** [comment]
There's a trace log, that is endlessly repeated:

TRACE async-std-1.8.0/src/task/builder.rs:57 spawn
TRACE async-io-1.3.1/src/driver.rs:187 block_on: waiting on I/O
TRACE async-io-1.3.1/src/driver.rs:75 main_loop: sleeping for 75 us
TRACE async-io-1.3.1/src/reactor.rs:204 process_timers: 0 ready wakers
TRACE polling-2.0.2/src/lib.rs:381 Poller::wait(_, Some(1.006810566s))
TRACE polling-2.0.2/src/epoll.rs:108 wait: epoll_fd=4, timeout=Some(1.006810566s)
TRACE polling-2.0.2/src/epoll.rs:96 modify: epoll_fd=4, fd=6, ev=Event { key: 18446744073709551615, readable: true, writable: false }
TRACE async-io-1.3.1/src/driver.rs:217 block_on: sleep until notification
TRACE async-std-1.8.0/src/task/builder.rs:57 spawn
TRACE lapin-1.6.2/src/io_loop.rs:222 io_loop do_run done; can_read=false, can_write=true, has_data=false, status=Initial
TRACE polling-2.0.2/src/lib.rs:423 Poller::notify()
TRACE polling-2.0.2/src/epoll.rs:186 notify: epoll_fd=4, event_fd=5
TRACE lapin-1.6.2/src/io_loop.rs:191 io_loop run
TRACE lapin-1.6.2/src/socket_state.rs:123 Got event for socket: Readable
TRACE async-io-1.3.1/src/driver.rs:75 main_loop: sleeping for 100 us
TRACE lapin-1.6.2/src/io_loop.rs:196 io_loop do_run; can_read=true, can_write=true, has_data=false
TRACE polling-2.0.2/src/epoll.rs:96 modify: epoll_fd=4, fd=3, ev=Event { key: 2, readable: true, writable: false }
ERROR lapin-1.6.2/src/io_loop.rs:358 Socket was readable but we read 0, marking as wouldblock

**Comment by Keruspe** [comment]
Thanks for all the details, I'll give it a look soon.
Are you using TLS ? I experienced similar issues and somehow switching to rustls "fixed" those

**Comment by davidhorac3** [comment]
Without TLS. I'm using an unsecured amqp protocol.

I can at least provide minimal runnable example at which I encounter this error:
[https://gitlab.com/IceExplosive/lapin-test](url)

Starting with `make init` and then restarting rabbit container `make restart` results with error above (as rabbit doesn't restart within given 2 seconds)

**Comment by Keruspe** [comment]
Which OS are you running? I cannot seem to be able to reproduce any of this here

**Comment by davidhorac3** [comment]
Ubuntu 19.10

**Comment by davidhorac3** [comment]
Interesting, when I run rust app from docker image library/rust:latest (which has Debian GNU/Linux 10) it works without a problem.
Reconnecting after rabbit restarts like a charm.

**Comment by Keruspe** [comment]
Could you retry on an up to date ubuntu (20.04 LTS or 20.10) ?

It it's still a problem on those, this might require further investigation, but if the problem is only present on an outdated version of a distribution, I don't think it's worth it

**Comment by davidhorac3** [comment]
Wanted to try it out today, but run into a new problem, after update I can't no more run an async_std version of lapin... Doesn't seem to be lapin's problem, but I keep getting an error:

no method named `with_async_std` found for struct `ConnectionProperties` in the current scope

The import `use async_amqp::*;` is marked as unused now. (No change in code)

Don't you know by any chance what might cause this?

**Comment by davidhorac3** [comment]
Well... using `extern crate async_amqp` solved it... and it works even after deleting it now (maybe something went wrong within Cargo.lock?) 

Anyway the error is not happening in Ubuntu 20.04. No idea what caused it, but no longer an issue.
Thanks for response and have a nice day.
