### ISSUE TITLE
Configure protocol version to 1.0.0

### ISSUE THREAD

**Issue by damienpontifex** [CleverCloud/lapin#318]
I was wanting to use the lapin library and use AMQP 1.0.0

I was looking around in the `Connection` and `ConnectionProperties` classes, but couldn't see that it was configurable anywhere. 

Would you be open to this being configurable, vs it seems the current default is 0.9.1, for a scenario such as this?

**Comment by Keruspe** [comment]
AMQP 1.0.0 and AMQP 0.9.1 are two entirely different protocols.
The name is the same, but they share basically nothing in common.

**Comment by damienpontifex** [comment]
Ahh there you go. I'm still very fresh to amqp, so thank you for the info and quick reply

**Comment by Keruspe** [comment]
The mechanism to change the protocol is there (just not exposed), but the protocol for 1.0 is not implemented yet.

I think ntex-amqp provides an AMQP 1.0 client
