### ISSUE TITLE
Support "connection_name"?

### ISSUE THREAD

**Issue by 6xzo** [CleverCloud/lapin#319]
Would you support "connection_name", as described here? https://www.rabbitmq.com/connections.html#client-provided-names

I have hacked this locally by adding an optional string to `ConnectionProperties` and adding it, if set, to the client capabilities table in `Channel::on_connection_start_received`. But I don't claim to understand this deeply, and I am on an older version (1.4.2).

```
if let Some(client_name) = options.client_name.as_deref() {
    capabilities.insert("connection_name".into(), AMQPValue::LongString(client_name.into()));
}
```

**Comment by Keruspe** [comment]
You just need to fill the "product" and "version" fields in the client_properties

**Comment by Keruspe** [comment]
Oh, wait, this is something else, I always thought those were the same, sorry about that

**Comment by Keruspe** [comment]
Ok, so it seems this goes in the same place as product and version though, in the client_properties field of the ConnectionProperties

**Comment by 6xzo** [comment]
In fact, that is what I first tried, adding this to the client properties table at its top level. But that does not work, and the broker rejects the connection. Reading carefully in the linked RabbitMQ documents, note that they say `Connection name must be specified using the "connection_name" field in the client capabilities table.` The "client capabilities table" is a table-typed field within the client properties table, as shown later in those docs (but without an example of setting the connection name) and, as far as I can see, only set within the `Channel::on_connection_start_received` function and with no user-accessible way to set the connection name.

**Comment by Keruspe** [comment]
Which version of rabbitmq are you using? With my commit, the pubsub example works fine and is shown as "pubsub-example" in the rabbitmq interface

**Comment by Keruspe** [comment]
Did you maybe use a ShortString instead of a LongString when testing?

**Comment by Keruspe** [comment]
If writing an AMQP client taught me one thing: It's not because the official documentation is clear and precise that it is right. It is often clear and precise by mistake, wrongly documenting what is actually expected. Here is a good example of bad wording provising a very precise documentation... which is wrong. The impl from my commit is the right thing according the rabbitmq-server sources + my testing

**Comment by 6xzo** [comment]
It's quite possible I did try to use `ShortString` instead of `LongString` because, trying again now, I can add arbitrary fields to the client properties with `LongString`.

I've been off reading the Java and .Net client implementations, and I think (though I only read source and didn't execute anything) that your interpretation agrees with theirs.

Thank you.
