### ISSUE TITLE
support other clients that supports AMPQ

### ISSUE THREAD

**Issue by abdelmonem17** [CleverCloud/lapin#320]
Is this crate used only with rabbitmq or it can be used with other brokers like Activemq

**Comment by Keruspe** [comment]
It *should* work with other AMQP servers, it's just developed and tested using RabbitMQ. If you find issues with other implementations, please open issues and we can feature-gate some workarounds

**Comment by abdelmonem17** [comment]
@Keruspe  it works very well with rabbit but I just closed rabbitmq service and opened activemq service with the same host and port but didn't work can you check it and help because I didn't a good crate like this one for amqp.

**Comment by Keruspe** [comment]
Oh, actually, activemq is an AMQP 1.0 implementation. Despite sharing the same name, AMQP 1.0 and AMQP 0.9.1 are two entirely different protocols

**Comment by abdelmonem17** [comment]
Ok thank you for help, can you suggest crate to create activemq client , also what is the support brokers for AMQP 0.9.1?
Thank you in advance.
