### ISSUE TITLE
AMQP soft error: PRECONDITION-FAILED: invalid ack recevied

### ISSUE THREAD

**Issue by zbrox** [CleverCloud/lapin#322]
This is more of a question and I can't quite figure out how this can happen. I'm getting this error on the regular now.

```
AMQP soft error: PRECONDITION-FAILED: invalid ack recevied for inexistant delivery_tag 124082 on channel 1
```

Anybody has any idea where I should be looking or what can be a common mistake that would lead to this?

**Comment by Keruspe** [comment]
Heh, nice typo in the error message.

So, this is when receiving an ack from a channel with publisher confirms enabled using confirm_select, right?

**Comment by zbrox** [comment]
Yeah, correct. It's set like this

```rust
channel.confirm_select(ConfirmSelectOptions { nowait: false })
```

The channel also has standard QoS options and a prefetch count set.

**Comment by Keruspe** [comment]
So, given deliverytag is an u64 and its max value is 9223372036854775807 I guess we can rule out the "overflow" hypothesis.

Do you put the channel in confirm mode as soon as it's created?

Given this fails with e.g. delivery_tag `124082` that would mean that `124081` successful acks were handled before...

How long does it take you to get to this error? Any change you could reproduce with logging enabled and share the last few hundred of logs? (Maybe privately if there is sensitive data)

**Comment by Keruspe** [comment]
Just released 1.6.7 with an extra trace log that could help track this down

**Comment by zbrox** [comment]
Yes, the channel is created and immediately after that it's the confirm_select call. 

So far the problem is that this is happening very intermittently. Sometimes it's not happening for hours, sometimes in the first several minutes. I haven't found anything to help me easily reproduce it.

I will try to update to 1.6.7 today and see if I can get something more in the logs.

**Comment by Keruspe** [comment]
Actually, I'm just going to release 1.6.8 with some more info in the specific error message you're hitting, even without trace

**Comment by zbrox** [comment]
Great! Thank you!

**Comment by Keruspe** [comment]
(FWIW, I have a test running at ~ 50k msg/s, currently at 15_000_000 messages and still haven't been hit by this)

**Comment by zbrox** [comment]
I've updated to 1.6.8 a bit after you released it and allowed the env logger to display lapin messages. Since then (~2.5 hours) it's been running smoothly and I haven't seen it happen. Delivery rates are much smaller but still around 2-3k msg/s.

No other changes were made. This is really puzzling :) I will update here if it indeed shows up again.

**Comment by Keruspe** [comment]
I guess no news means good news?

While I was doing some digging for this, and adding logs, I also merged two things that shouldn't been split anymore, and this might actually have been the fix for your issue as it touched some locking wrt delivery tags (merging two locks into one as it should have been)

**Comment by zbrox** [comment]
Yes, thank you. I was pondering the same, but hadn't had time to look into the change from 1.6.6 to 1.6.7. This is running great currently! More than 3 days of uptime. Thanks for your work!
