### ISSUE TITLE
amq-protocol new update breaking 2.0.0-alpha.2

### ISSUE THREAD

**Issue by Miaxos** [CleverCloud/lapin#326]
### Current behavior

I'm using `2.0.0-alpha.2` in my Cargo.toml, and with the new upgrade from amq-protocol https://github.com/CleverCloud/amq-protocol/releases/tag/v7.0.0-alpha.7 which remove this part https://github.com/CleverCloud/amq-protocol/compare/v7.0.0-alpha.5...v7.0.0-alpha.7#diff-5b49c34820eb7d91c1e259b4ec4da603c4091c9335f4b894713b670c3bfd28feL211-L218 it'll break existing 2.0.0-alpha.2 usages because the version is from february and it'll use the latest alpha from amq-protocol (which is breaking).

![image](https://user-images.githubusercontent.com/1060101/112834417-3e533000-9098-11eb-8bf7-bdef7d3ad2fe.png)

### Steps to reproduce the bug

Just use lapin 2.0.0-alpha.(1|2) in a rust project and it won't compile. (Or you have to specify the sub dependency amq-protocol to use the previous version.

### Possible solutions

Juste release a new alpha, with the latest commit from master it should work.

(Awesome lib, thx for your work ! 😄 )

**Comment by Keruspe** [comment]
Heh, it was meant to be pinned on a specific alpha.

Will make a new release fixing that

**Comment by Keruspe** [comment]
Thanks for the report
