### ISSUE TITLE
Hang on next ack after double-ack

### ISSUE THREAD

**Issue by teozkr** [CleverCloud/lapin#327]
# Repro:

1. Send two messages to a queue `hangtest`
2. Clone and `cargo run` https://gitlab.com/teozkr/repros/-/tree/lapin/consumer-hang

# Observed behaviour:

1. Channel is closed because double-acking is a protocol violation
2. First `ack` of the second message hangs because the channel is gone at this point
3. Curiously, the hanging ack never even shows up in Wireshark

# Expected behaviour:

There seem to be several problems causing this bug, which should be fixed separately:

1. `ack` to a closed channel should fail with a channel-closed error, rather than hanging
2. Maybe `Acker` should raise an error if it has already been acked (or `ack`/`nack` should consume the `Acker`?)

**Comment by Keruspe** [comment]
Nice one thanks!

Will give it a look later

**Comment by teozkr** [comment]
Another weird thing about `acker`:

https://github.com/CleverCloud/lapin/blob/84ea4a569e213c5769b084fe2dcaa5d97e1b860f/src/acker.rs#L48-L54

This will deadlock if `self.internal_rpc` is `None`.

**Comment by Keruspe** [comment]
First I want to take the opportunity to fix the hang properly, then I'll add some client side error preventing this from happening

**Comment by teozkr** [comment]
Sounds like a reasonable path forward.

**Comment by Keruspe** [comment]
Here is what I get here:

```
module: lapin_consumer_hang:17
 Apr 08 17:09:38.294 INFO Connecting
module: lapin_consumer_hang:23
 Apr 08 17:09:38.299 INFO Connected, opening channel
module: lapin_consumer_hang:25
 Apr 08 17:09:38.663 INFO Got channel, opening consumer
module: lapin_consumer_hang:34
 Apr 08 17:09:38.664 INFO Got consumer, listening...
module: lapin_consumer_hang:37
 delivery_tag: 1
  Apr 08 17:09:51.450 INFO Got message, msg: [102, 111, 111]
module: lapin_consumer_hang:40
 delivery_tag: 1
  Apr 08 17:09:52.452 INFO Acking
module: lapin_consumer_hang:42
 delivery_tag: 1
  Apr 08 17:09:52.452 INFO Acking again
module: lapin_consumer_hang:44
 delivery_tag: 1
  Apr 08 17:09:52.453 INFO Acked message
module: lapin_consumer_hang:46
 Apr 08 17:09:52.494 INFO Consumer closed
```

**Comment by teozkr** [comment]
@Keruspe

You need to send both messages before starting the consumer. `Consumer`'s `impl Stream` will (correctly) close the stream once the channel disappears.

**Comment by Keruspe** [comment]
Ok I reproduce now, indeed

**Comment by Keruspe** [comment]
With your fix + my error propagation:

```
 delivery_tag: 1
  Apr 08 18:45:11.534 INFO Acked message
module: lapin_consumer_hang:37
 delivery_tag: 2
  Apr 08 18:45:11.534 INFO Got message, msg: [102, 111, 111]
module: lapin_consumer_hang:40
 delivery_tag: 2
  Apr 08 18:45:12.536 INFO Acking
Error: protocol error: AMQP soft error: PRECONDITION-FAILED: PRECONDITION_FAILED - unknown delivery tag 1

Caused by:
    AMQP soft error: PRECONDITION-FAILED: PRECONDITION_FAILED - unknown delivery tag 1

Location:
    src/main.rs:41:56
```

**Comment by Keruspe** [comment]
With some prior client-side testing: 

```
  Apr 08 18:45:56.358 INFO Acking
module: lapin_consumer_hang:42
 delivery_tag: 1
  Apr 08 18:45:56.359 INFO Acking again
Error: protocol error: AMQP soft error: PRECONDITION-FAILED: Attempted to use an already used Acker

Caused by:
    AMQP soft error: PRECONDITION-FAILED: Attempted to use an already used Acker

Location:
    src/main.rs:43:56
```

**Comment by teozkr** [comment]
Nice, thanks!
