### ISSUE TITLE
Can you release an alpha version from the executors?

### ISSUE THREAD

**Issue by augustocdias** [CleverCloud/lapin#328]
Hi,
I'm trying to use the alpha 2.0 version because of tokio upgrade to 1.0 and I'd like to use the executors as well. I see that you already have them implemented but they're not published to crates.io. Could you perhaps release an alpha/beta version of them?

**Comment by Keruspe** [comment]
tokio-amqp 1.0.0 depends on tokio 1.0 without the need of switching to lapin 2.0 alpha.

Also, it will be deprecated once 2.0 is out, so I'll just make one release alongside the final 2.0 with everything inside deprecated.

The "new" recommended way of doing this with lapin 2.0 is to use tokio-executor-trait and tokio-reactor-trait and to use `ConnectionProperties::default().with_executor(tokio_executor_trait::Tokio::current()).with_reactor(tokio_reactor_trait::Tokio)`

**Comment by augustocdias** [comment]
and what does lapin 2.0 uses if I don't set any executor in the properties?

**Comment by Keruspe** [comment]
It uses the same internals as async-std by default
