### ISSUE TITLE
method not found in `(lapin::Channel, Delivery)

### ISSUE THREAD

**Issue by universon123** [CleverCloud/lapin#336]
Dear Keruspe:
Thanks for your this great crate!
when I run this example, pubsub.rs, it get an error,like this:
      no method named `ack` found for tuple `(lapin::Channel, Delivery)` in the current scope

How to fix it?

**Comment by Keruspe** [comment]
How do you run it? Which version of lapin are you using? What is the complete error?

**Comment by Keruspe** [comment]
FWIW, the ack method is available on the Acker returned by Delivery::Acker
