### ISSUE TITLE
Can we specify a specific port for Lapin client connection?

### ISSUE THREAD

**Issue by videni** [CleverCloud/lapin#345]
My server would assign ports to customers,  I don't want Lapin select a port that might be taken or  assigned to a customer but not used at the moment.  it is possible to specify port for Lapin connection please?  I am sorry , this question is quite stupid.

**Comment by Miaxos** [comment]
Yes you can, by just defining the port inside of your URI as described in https://docs.rs/lapin/2.0.0-alpha.4/lapin/struct.Connection.html#method.connect

``` rust
let uri = "amqp://127.0.0.1:5672";
let conn = Connection::connect(uri, ConnectionProperties::default().with_tokio()).await?;
...
```

**Comment by videni** [comment]
thanks, I mean the client side ephemeral port,  I realized later , we can specify ip range of linux for.ephemeral port.
